version: '3.9'

name: spec
services:

  psql:
    container_name: psql_news_db
    image: postgres:15.4
    ports:
      - "5437:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_db
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: