server:
  port: 8282

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/news_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: on
    change-log: classpath:/db/changelog/db.changelog-master.xml
